/*events->>The changes in the state of objcct is known as an event.

Events are fired ton notify code of 'interesting changes' that may affect code exicution.

-Mouse events (click,double click etc);
-Keyboard events(keypress, keyup, keydown)
-Form events (submit etc)
-Print event & many more*/

//event handling by js
//event handling by js is more powerfull than inline event handling

let btn3 = document.querySelector("#btn3");
btn3.onclick = () => {
  console.log("You pressed...");
  btn3.innerText = "You Pressed";
  //btn3.textContent = "You Pressed"
};

btn3.onclick = () => {
  //if we handle on object two by this type of function the latest function override  the previous functions...For this reason-> we havve a best way of handling which is addEvenListner("event", function pass)
  console.log("You clicked me...");
  btn3.innerText = "You clicked";
  //btn3.textContent = "You Pressed"
};

const box2 = document.querySelector("#box2");
box2.onmouseover = () => {
  box2.style.backgroundColor = "rgb(100,230,230)";
  alert("You are inside div...");
};

// event object
//It is a special object that  has details about the event.
//All event handlers have access to the event object's properties and methods.
let btn5 = document.querySelector("#btn5");
btn5.addEventListener("click", showEventObjectInfo);
function showEventObjectInfo(event) {
  console.log(event);
  console.log(event.target);
  console.log(event.type);
  console.log(event.clientX);
  console.log(event.clientY);
}

/*Event listners -->>>
node.addEventListners(event,callback)
node.removeEventListners(event,callback)

**the callback reference should be same to remove
*/

let btn6 = document.querySelector("#btn6");
btn6.addEventListener("click", () => {
  btn6.innerText = "Clicked Me for addEventListners";
  console.log("Clicked Me for addEventListners");
  alert("Hello, I am here.....")
});


let btn7 = document.querySelector("#btn7");
btn7.addEventListener("click", forRemoveEventListners);

function forRemoveEventListners() {
    btn7.innerText = "For add Event Listners...";
    console.log("Add event listners");
    alert("Event listners is added.....")
  }


  //to remove event listner,,,,you have to pass same function which is present at same memory location....for you need to store the callback function to a variable

  btn7.removeEventListener('click',forRemoveEventListners);


//   Practice question-> Create a toggle button that changes the screen to dark-mode when clicked and light mode when clicked again


//The below code is generated by myself
/*  
let button = document.querySelector("#mode");
let body = document.querySelector("body")

let mode =  'light'
const changeMode=()=>{
    if(mode === 'light'){
        mode = 'dark';
        body.style.backgroundColor = "black";
        button.innerText = "Dark";
        button.style.color = "black";
        button.style.backgroundColor = "white";
        body.style.color = "white";
    }else{
        mode = 'light';
        body.style.backgroundColor = "white";
        button.innerText = "Light";
        button.style.color = "white";
        button.style.backgroundColor = "black";
        body.style.color = "black";

    }
}
button.addEventListener('click',changeMode)
*/





let modeBtn = document.querySelector("#mode");
let body = document.querySelector("body")
let currentMode = 'light';

const changeMode =()=>{
    if(currentMode === 'light'){
        currentMode = 'dark';
        body.classList.add("dark");
        body.classList.remove("light");

    }else{
        currentMode = 'light';
        body.classList.add("light");
        body.classList.remove("dark");
    }
}

modeBtn.addEventListener('click',changeMode);






